
package sakine.ayoub.proxy;

import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ReleveWs", targetNamespace = "http://services.ayoub.sakine/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReleveWs {


    /**
     * 
     * @return
     *     returns proxy.Releve
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "myReleve", targetNamespace = "http://services.ayoub.sakine/", className = "proxy.MyReleve")
    @ResponseWrapper(localName = "myReleveResponse", targetNamespace = "http://services.ayoub.sakine/", className = "proxy.MyReleveResponse")
    @Action(input = "http://services.ayoub.sakine/ReleveWs/myReleveRequest", output = "http://services.ayoub.sakine/ReleveWs/myReleveResponse")
    public Releve myReleve();

}
